apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: core
  namespace: argocd
spec:
  description: Core infrastructure (metallb, ingress-nginx, sealed-secrets, monitoring, argocd)
  sourceRepos:
    - "*"
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"