{{- if .Values.sealedSecret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "app-base.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app-base.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{- toYaml .Values.sealedSecret.encryptedData | nindent 4 }}
  template:
    metadata:
      name: {{ include "app-base.secretName" . }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
