apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-base.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app-base.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "app-base.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ if .Values.nginx.enabled }}{{ .Values.nginx.port }}{{ else }}{{ .Values.fpm.port }}{{ end }}
      name: http
