apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
spec:
  project: services
  sources:
    - repoURL: https://community-charts.github.io/helm-charts
      chart: n8n
      targetRevision: "*"
      helm:
        releaseName: n8n
        valueFiles:
          - $values/n8n/values.yaml
    - repoURL: git@github.com:justgu1/kubernetes-services.git
      targetRevision: main
      ref: values
    - repoURL: git@github.com:justgu1/kubernetes-services.git
      targetRevision: main
      path: n8n
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true