---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    admin.password: AgDNlaRjgUPNosZInpl4XBVS1r6SAIvmQtG3noo8Eq9kFGqrblHUHwYhrJfh14DQUPlil20Mm2tz1coWJRunsnbAsFI6L9Tx0lqvPmvlfn5dcON9xbk3Lvgz8N3GBz8F+F1KEnrr5IZrO7wNqLo6MK/ALo8GARAsWXHw1HYJxfklZZj9seQgyXbnoFPoFwdl1KtSfAoJXT2uC5NI6t226BO4+m+cOj1DdnhMyCqLX6/v9a11PHuuzc9MwqwoRpEWVLzafgE02Vpue0KSEVQQU9iogML+a2JRgnpP0QRcwkK73vFmbiCyo1iOp3N030WfZOaPV8zRMLTZ1LMV5cjoPLh0Va9QLUVwGVSvbrpEOn5C/JzzOqsRzPGPk5sBAAqj8zKnDX3xSdMlfkFZQ8Fk4l2LeW+lfzwqVMjCQt1LP5OkrEau575TYslE1311GUYR+8fTyXCoGhxerEJtkJLd0A7c79gcYPU8xovPydxu7TeW67UlP5gCjMbZG1vUYUnJBihVryr6ChUOw6IHdtJBBP9vofvIwWMipWjtKV+7whV4rM5TWb1x+79S863lbccnSE/4XVI/gDx8Q3FhpKDHfP58VsynOokukZ0cttTgUNqKwn9JHPZcbDFoCABi6M60Xa1I/YJXQ27WSTDwmbrUl0pRF+qYERYWLgjo4IAhTNFBm8fPGTyWjwzmI/+yYQfaxWRpWLljqIujaMfSqiojBTwh7ltxALfDXL/9ZNgtEwqFUiPiw6WlOcNLrfnd72udorhfU0gJJ/R7+ElUTJM=
    admin.passwordMtime: AgCqNI7DYpf4KSg9EB0U6WMslITKyUH5HiODlRtYbmAViKUqjCInQxj3DyKhf1eNm4xdIHIxd3e/gAEz1DzaU2Mf1LcEqKjXzEtOD9cW0HxUOKwnz2PFwBnVcF3UmrH/501uMoKg3JtKeBq75eQiUsShE6RVHBpW58oRkxYYbeLxRnfysFvYMv0g73ZvsGmpBdE4jw47L2eaQ1Lo86UFP8XK1LBXqmibTKDu5b9Ve5pKDZXRzogdX4c1AJpPzEmmfQOCd+OoxIQcEl7x2hZgPKTmEVZyhHvi65nWkDV/QepqnVMUxjX51Jm+s2VtUFVppSnoluzgMQZAepFMdYWuDNQkUYr4bXtmLxV3KzKqLs7M2YYoBtcwRmJD4GvFStMk1JJ41zw/xIR47MZueTmIfvKhnYgOKj8B070OpAFj1POuticFSzCNp8ybTqkInzEFu2LlIZkmwp6FMtmZav4ZQyk9Q24iI8bEhqkRnE265aNYbrHqCG9wzIg9ph+/XCngMbt9YazarIl3EVVzE2BvcyDu1T5AbxIn8Ur/LpyyV55AwrkCq1XatM1g/X4cPh40N6Q0zxY1eD5newfEWZlgW29CMJHyjIRvIn5LFKkq/2EVBHQ+jMm4ubmeCf4BhGXZGgwdrPxkezooYdvLIK4BMvmGOc8F+FcbhX5rwI2dDFctHTYwXRhwfqIMkw6vEHZBwM/qrG86HBRrGya8FBZKU2qgmuALFwn6
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
