---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    admin.password: AgA/2M/K7Ap4JzVMhvbU0kg7wtN+Y5HxC0iLg+miN7BD7GVsrfkKQHY1V9grIyQDyOi0uFCWoI71e7O0eOY8xh7Npy9H8Xak8oSHHGzOG+fn5lR/8wo2+zcaogIJBILE7l4LX7AhyJ5cc6NSKPbrA7+79Hn/TI+PHZPVapXG+y52NdsiLRvbd/QqsDTjGs7N++ZjhAjj2be9YwNhU7ZlfgcBRVXzd5AG6Hn2t8fPiYB71v4nnMknC2fzz0+K606bs5DMOOOX/nC78xzBJqhLuI4/SGOW36xZrWTmi2CXnpRwo+tzGpgpFGqAAsAg2Yvhx5vhB4/xY4HYBrgpMUsSeXUuiCwzVrQg4yOqImYN5LnbD07nVPB6ytvil0ES4m1xxjjaTeVWP2Dqpv73AyEJ1fhx8bE8bkvND1kfPf1rYWTCNF/JimhU4O2utKveApPg3U1w2s3ffYIJIzy2LIOTfLAI3ISotCzNFyRqFJbdnIKu4BZR8qf5kY+YNW0OVXF7ZmM4gPkXxb1M5LgEZKJr48KZXI82IUGK9x0NzhRXqxFjQVp0WIg/DaPhohplZ/m0y7hb77SRTW4qKcdVDfzHTlfjvpLsZc3Jxp6z4Z3fqLr6szRQNx1i5ysr8ydhFFfCheHq8edQwfE0tonbgtz7xr9YovTW7wRdEBC2jJqXxR6WcgfvmDU4yc1iafmZdLcwuTfd6HJio9qUnz/VrVxW31qbWvuyLx6qgTRvKE5rr360p/zjMedUTEJb/T3nlYWKMrifhV6RZHKDRqYkRLY=
    admin.passwordMtime: AgAUcw6JTzod8KmxzsXAy8+4fDa+TC+b3zseV30zIJsKQCVlcf57Yf7fy39w0Lcl2NULqTnyyPqMnpBF+fh9yhNPoLDyF5seR5bINcHH4O8fpX5NcDWlE+KifNpBKbpnxiqc8YeHAK8yNMQ92wpH/s9A29crgrw4nFcyMlzi9Lr8sYPHVwrEEMVEROdZnYaRCOe0ipvVZFkHY5L5yhVkzCTY4Qck1psPydONByjDUXd8IzD6mREUkn622tZOXwPMB5nzbzI+k/UE6vD59xHUhvSx2Ln4PGPpxe4s/P6si0oi+jXeP7cm3AcHHToRI7n8W0KD70J5vKPlEpwA4udDw77YkD/WPwOJozm8AiuQb5WRgHxhGnMoIinqoxtuXUD0AXtiD0fWP26f2auBVv6EN/fpxPfPXX2HUGE6rfl7jCumydH61pQAdwkR2NgiUX5DCI0+Jct6rz6Ts2ylGhF8lsVZLq1pGESesFPiw2yiN+8IAyDRvSBLPsXtIZcb6zAo/xG2dToA06KESM4sBiZ0McqNie7TU4t3uKaI3QBCW1zHln6SM/PxCbJ/+N9t2gypU8jry1+odeXTDSdXvWuitiZjVGfAIA6GsoT8y6wM+RxJOn4uG5TTcA7eNJRsJSfhAXyC8hwo7gmIdz6sxNBw8ixkiZrMeL7Lutwiz8YoN5ZzG10SfYjeIMn0rzH5uXI07POezV61C2290ZDkFChkpdmOdWSEmqRr
  template:
    metadata:
      creationTimestamp: null
      name: argocd-secret
      namespace: argocd
