---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-github-secret
  namespace: argocd
spec:
  encryptedData:
    oidc.github.clientSecret: AgAH+Uzlg7/tJtuWVWKvFzFVNLTTetbj2wPjyQznEGTBF1aBcsiXzWtjNrXAlfBLYbL/cc/Wefqus4+6Ix1WWWGa/inPRGQ3KtGGsqH+qs43dIl4IBVwr1ah4eIoCOBEhOuRFI6AHb5Csz2y06Q8xXdlHkSkxb4F5Z+UDoY7U6+wEzqtpkhjCNJKAaTtlZgFHANaDrc/USfTm+1SZGsdvAi5MCc0vjBQbFJbSWZ/rsfXnQszWzYLskeOZunwyN8gpmoLN8Hs33XHSQQNrx/iwe+9Ub069pi5RlKNYmhnqnHEEMvM7T526GCYX2McOjAdEUt1cTp/XDmKR62niqL5yqJutkXDzkMAwFW3+mYPxTZsZlWYxQZGQ4eiBEzVQrqzhdI6h8dgpvQg48g0yeNpGyW/XZlznpYicAYUhFFPQp8FJRWseBDyQS40SedPx1yX6JFPiDipsFQohAMJks2WDKy7qd+6KJ30zYDZFt6bKrawZ/MhUp+sSL0PrjP1RNYgKvRI3OIFew5DJ6GHm9lm+7sWbPe/F1cpo0AS3Y6iULRBQoAEIHE6l/Txt9HILpHH4N2A0mDiVnF23UpCjYShyDP0aiL0GoxvWu1ZF4zHDWRT/+UMi1KJ8uJ78nMXAqlgqP22NQPvOLiRVK0Vfyo2O5r/W0OFyJlNwk9H5dkOnzUOUCnltI2cY1rhfKWoaAf69GRoSgGmqcRNvb4oz4+XQXz+74vzIPbZ47TxU/SCJfW/QL3XM5iBhLOL
  template:
    metadata:
      creationTimestamp: null
      name: argocd-github-secret
      namespace: argocd
    type: Opaque
