apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 9.4.10
    helm:
      values: |
        server:
          extraArgs:
            - --insecure
        configs:
          cm:
            url: http://argocd.local
            dex.config: |
              connectors:
                - type: github
                  id: github
                  name: GitHub
                  config:
                    clientID: Ov23liFXjakC9R71jUAJ
                    clientSecret: fc356f4725cc053bd2bcc9e9933ad66ab1999eb1
                    orgs: []
          secret:
            extra:
              oidc.github.clientSecret: fc356f4725cc053bd2bcc9e9933ad66ab1999eb1
          rbac:
            policy.default: role:readonly
            policy.csv: |
              g, justgu1, role:admin
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true