apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: core
  sources:
    - repoURL: git@github.com:justgu1/kubernetes-core.git
      targetRevision: main
      path: argocd
      directory:
        recurse: true
    - repoURL: https://github.com/justgu1/infra
      targetRevision: main
      path: core/argocd/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 0