apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 9.4.10
    helm:
      valuesObject:
        server:
          replicas: 2
          extraArgs:
            - --insecure
          autoscaling:
            enabled: true
            minReplicas: 2
            maxReplicas: 5

        repoServer:
          replicas: 2
          autoscaling:
            enabled: true
            minReplicas: 2
            maxReplicas: 5

        controller:
          replicas: 1

        redis:
          enabled: true
          replicas: 1
          master:
            persistence:
              enabled: false

        redisSecretInit:
          enabled: false

        dex:
          enabled: true
          # Injeta o clientSecret do SealedSecret como variável de ambiente no pod do Dex
          env:
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: argocd-github-secret
                  key: oidc.github.clientSecret

        configs:
          cm:
            url: https://argocd.justgui.dev

            server.disable.auth: "false"
            server.x-frame-options: "SAMEORIGIN"

            # Dex como broker OIDC para o GitHub OAuth
            dex.config: |
              connectors:
                - type: github
                  id: github
                  name: GitHub
                  config:
                    clientID: Ov23liFXjakC9R71jUAJ
                    clientSecret: $GITHUB_CLIENT_SECRET
                    redirectURI: https://argocd.justgui.dev/api/dex/callback

          rbac:
            policy.default: role:readonly
            policy.csv: |
              g, justgu1, role:admin

  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: applicationsets.argoproj.io
      jsonPointers:
        - /spec/preserveUnknownFields
        - /spec/conversion
        - /spec/versions

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true