apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    dex.github.clientSecret: AgC6/nr13+r5jN+Fbzv1wBp+AIMmt/jZAO9qK0ZtBXYtSbO/Mzt2CYJuTV5UcbpJfHdOQxqfZrDilXQ9lIEQPZ8Q0UnUt21r2FDWzytZCi8gxLoM3DBluVmC5h9QaFJfY9nG0TcbJBJaQjpO3ihKZDNy4Jhj3NRb/726y5eBbgIdB3S9rDNOG+lR1oCSCgTkOrLs5w3DumrJg7ZifK4qtep5DFBLD6ATFmga90pxlosC51+yaqu6UHTOKKsiPqlRCO2UjXMn/Z1FRvy3FSO3Y8EgyJbwHeGbu5FJXnQRpCm1ezVa7tNiL99SFRNQv6At9AdbghEJ4O9tYR3KD0Pkgxlew1So/+/MGb1rdV0ksHv6vhy+P/pSROvjMfOt8Zw8iX81BWdg4l07taeTk9Bpqjzum4/scdBjaMAVD1rBJQwPlOeTB8v3oRTHeEojDDobTq7I5qr4hOI70xaeWaiLs7bu0Rrck64fzm1nv+nqEiJEMtXLyu6hlUJdwQaHKtD/rQO5UJB/Pg7jr9g77LENhZh6iH53ZCwm5bp8ftRibhwxltWZn41basX3603jRW4eoeErMZtYohHz6kTNs398eaGRjphaD5B4hgmkgrxNlfyH5jFgc9DgTrN5CGHEsWSQDjOkNw4g/MmeglIY0ezvYVXPWcp6rC2r325VJ0e3L2BgVitiBkCBeoT/7cLvvjeCj62lBnj8gj2upv9AXOdp/xmpPX5iNpz+jcSvN15/Q4cV2H2q/cV8+rSo
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
    type: Opaque
