---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-github-sso
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgAqUHGVC4xiXTDtZmdzUF20Re3KOpwGtMEJvbsNaJMNkCqJ10s9FgdRfhDVbwzeeCQ7asSIGiD0npwBAMhVbJ12huRtJeQLeAuOqEz5YR5V/iHxtHLCiJGH2BaA0SABzomwoDXuvmpnNaZfL216NOR+pC73L0aIraT/SCRZjHdRl3aDbXrdjytVjqA1aA81DPI4gs+MvykGMqvlC9SLDHuBa6NfzvKvUYwRKntOYgJ4xO7H+5yVc06ZSQPXL3rW2OAtbCTc9VsUvcTsh9snxvsSwx5Wd7DEouVBM2ZDWMWJzHf/69l/4N60bhnE+uTjqBsjSIr+l5Xl68VWzEMuw7WCibleSk4f/JovcZVWkckzLF/dgQHxuo/UNP/iDY4jiD9ehj+NedrNCgIO6CubQgOR5uQwwVP8Uo/PZKH0oQuhxWu6Ko/gkHvVhe4hEUEDVuwQhuRGrJSwyg+gTC/DIn+r6IfEz00uhD31AzCwY6p86oXf5IUfiEe/LwIQ9/Qp1soteaAmmRfEn6zyRWACTpPSq6Ukbx+z/PmdRBJyyKXvD2i3Pg8Jr4SIkzbWfnR9hy2tzNzxd6BDKEkkxWZm5tkpjIdL059wolIn/cj+GbMJewYMyI+SgarwwaynNzo75iBY3oaZJOCltydlX5dIgXF70a9ehlaxzpn9CMwXvBW780rVvsEgCKB+g2OC9hcf6/QR1sm2e/Akysea6Ov1HoJsn3D+5kE1hHIy59f6ylQJeiwTQUR/MInl
  template:
    metadata:
      creationTimestamp: null
      name: argocd-github-sso
      namespace: argocd
