---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-github-sso
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgANjGmtT99Pd1Pn+unimwjwYZ20o88D5H2DKlRmhUq2qEMKf4OcwADSElaBud8hJV6R1ByKZI5v/cdXAtxY6BXyVCVKLo09SpFFzSQRc9FG9QVTwNkAI1h9EFp0iD7kODMRtfRHWIKLN1BQk7i5hWcOtyxpzleN4aEotIWQA8KQWTjT+b27JVjHwuUI6ZcTE1Yrhs1wI40ujLVED6Fwwnr7G12XwSVDXGIXVLI4ISj7G/mRdbWoJ/gvNF/EGQpk3D2fv05F5C3xTtO2UXaQUVQvUZB2oAGdtV06U/R+5TA7RJ2SjQKqiL6OqM56FChdzXXfknLSTWKXmDDWlbe0MJEb3csBMp6kPlSfoMjiGY/mEDaFf3I2/V11dHE4iqMn7g3+2FRNn+gK1h3bM8Y7XIM2NGgJnkVFfdHOCZkoFSmAunHKDqji8ozspze0sku4p7AXECT7wf0knVxtL+4qIJ/b1ibLpsRPDpCaMgohlLvw2z+MAhYQsaa4DIaxdm5Ac0dEweS579+qDCUtw+jZgDmquS/6exRFN31eNLKp1Ix9t7ySMpiyRrqKSifZjP4IuBAfiZf3YhrB14dzmJre4/FI9up8poBbuNqCj7qEI2A2mVgEZLtAwx2rgurFrf5KeXfPu5T52XlxvD8MzdIdUEz7xWW3NjujN0cHVlls3HEydZ0nhVc5m71xecnkXreeUBU7SNTooYBoNAJIlzgEGqixCYL5v2jNx8Uqn8NbLVv7MFRIThla+s2S
  template:
    metadata:
      creationTimestamp: null
      name: argocd-github-sso
      namespace: argocd
