---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-github-sso
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgB0n/jukJy3gt2kTff1a8vcFs8MFaLhN5bmD+BGcKEy3iWPArYrJPTCFWOhlGkhNCdbUB+fAfxC7s0QNNa/cTtcS3eOg2eHTQ9QsaRV9VjOSgVFoeVA/rs4hNkL4D51NB+TsvPwFnuhofN/FnIIMHuN6K4L180kSkbH/v7d6/MmuboUwwk53VmiinqM4iNaXUJ/x3Qxyb7xYdx7SI9zAyj128xZNx8GMwuJ+oYmXoP9877HbJ+tZ//z0C8IxzrNTU+HvMllmd1h7Cmtkm6eAgshWSwiO/GXsonlC4C674IrE4mv44l9bjuCeuzSCFSDkm6+YA3L+48K5e8xRPeNBVuLkJuijmVfo1Y/KOx+aSQ4MZMlNLHej6HfTFsq0cbmN+UKKh+d7gxGRsXwRuA6W6UinClRYPUdGaWGyp2smPC5QH9jiQVXQwV6VaLzd3LFHS/BMg7tKWzCK2YqHvPqwhXg/vXlheG4xxwJuUb7In0vY808r2CgLP+MFp5TUGvxpJnhA+wyblkUB+IXPW7/IlWK3ZtKXQA1X6bqzI/NIqkKaIULh9ktsIqZUW1CY1y0hCKyEZlYsMw+v5OduIctFaU8vh/vIF4ukkeILXfVPOrPLntnQ5ImfMvPTA8bxdIeoC5qkbQ4vBg7dPS/F/J5h2MpMGMT0yzc/Ul4bQHAJiH8f/Do4AyAaTU63L0dvuZ4flymmChtS9TDq2eDJasKOiP9uwflsEBaPv1TgZbV1WxtBxhYjcWbwnoU
  template:
    metadata:
      creationTimestamp: null
      name: argocd-github-sso
      namespace: argocd
