apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: listings-updater
  namespace: argocd
spec:
  project: apps
  source:
    repoURL: git@github.com:justgu1/justgu1.git
    targetRevision: main
    path: apps/listings-updater/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: hericarealtor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
