apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: passbolt
  namespace: argocd
spec:
  project: services
  sources:
    - repoURL: https://download.passbolt.com/charts/passbolt
      chart: passbolt
      targetRevision: "*"
      helm:
        releaseName: passbolt
        valueFiles:
          - $values/passbolt/values.yaml
    - repoURL: git@github.com:justgu1/kubernetes-services.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: passbolt
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true