apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - infrastructure.yaml
  - metallb/application.yaml
  - metallb/config.yaml
  - ingress/nginx.yaml
  - monitoring/monitoring-app.yaml