apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-oauth-sources
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: authentik-oauth-sources
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: cluster/authentik-oauth
