apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: services
  source:
    repoURL: git@github.com:justgu1/kubernetes-services.git
    targetRevision: main
    path: minio
    helm:
      chart: aistor-operator
      repoURL: https://helm.min.io/
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true