apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-projects
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/justgu1/infra
    targetRevision: main
    path: k8s-projects
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true