apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: listings-updater
  namespace: argocd
spec:
  project: apps
  sources:
    - repoURL: git@github.com:justgu1/infra.git
      targetRevision: main
      path: charts/job-base
      helm:
        releaseName: listings-updater
        valueFiles:
          - $values/apps/hericarealtor/jobs/listings-updater/values.yaml
    - repoURL: git@github.com:justgu1/infra.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: hericarealtor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
