---
# ClusterSecretStore — permite que qualquer namespace leia secrets do Vault.
# O ESO usa AppRole auth para se autenticar.
# O roleId e secretId ficam no vault-eso-auth Secret (criado pelo init job).
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      path: secret
      version: v2
      auth:
        appRole:
          path: approle
          roleId:
            secretRef:
              name: vault-eso-auth
              namespace: external-secrets
              key: roleId
          secretRef:
            secretRef:
              name: vault-eso-auth
              namespace: external-secrets
              key: secretId
