apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 70.4.2
    helm:
      valuesObject:
        grafana:
          adminPassword: admin
          grafana.ini:
            auth:
              disable_login_form: true
              signout_redirect_url: "https://oauth2-proxy.justgui.dev/oauth2/sign_out"
            auth.proxy:
              enabled: true
              header_name: X-Auth-Request-Email
              header_property: email
              auto_sign_up: true
            users:
              auto_assign_org: true
              auto_assign_org_role: Admin
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
