apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://oauth2-proxy.github.io/manifests
    chart: oauth2-proxy
    targetRevision: 7.7.1
    helm:
      valuesObject:
        config:
          existingSecret: oauth2-proxy-secret
          configFile: |-
            email_domains = [ "*" ]
            upstreams = [ "file:///dev/null" ]
            github_users = [ "justgu1" ]
            cookie_secure = true
            cookie_samesite = "none"
            cookie_domain = ".justgui.dev"
            skip_provider_button = true
            reverse_proxy = true

        extraArgs:
          - --provider=github
          - --cookie-domain=.justgui.dev
          - --whitelist-domain=.justgui.dev
          - --set-xauthrequest=true
          - --pass-access-token=true
          - --cookie-name=_oauth2_proxy

        service:
          type: ClusterIP
          portNumber: 80
          targetPort: 4180

        ingress:
          enabled: false

  ignoreDifferences:
    - group: networking.k8s.io
      kind: Ingress
      name: oauth2-proxy
      namespace: monitoring
      jsonPointers:
        - /spec

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
