apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: git@github.com:justgu1/kubernetes-services.git
    targetRevision: main
    path: authentik
    helm:
      chart: authentik
      repoURL: https://charts.goauthentik.io/
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true