apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: services
  sources:
    - repoURL: https://charts.goauthentik.io/
      chart: authentik
      targetRevision: "*"
      helm:
        releaseName: authentik
        valueFiles:
          - $values/authentik/values.yaml
    - repoURL: git@github.com:justgu1/kubernetes-services.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/justgu1/infra
      targetRevision: main
      path: services/authentik/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true