{{- if .Values.configMap.data }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "job-base.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "job-base.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap.data | nindent 2 }}
{{- end }}
