{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "job-base.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "job-base.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: {{ include "job-base.secretName" . }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.externalSecret.vaultPath | default (printf "secret/%s" .Release.Name) }}
{{- end }}
