apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatwoot
  namespace: argocd
spec:
  project: services
  sources:
    - repoURL: https://chatwoot.github.io/charts
      chart: chatwoot
      targetRevision: "*"
      helm:
        releaseName: chatwoot
        valueFiles:
          - $values/chatwoot/values.yaml
    - repoURL: git@github.com:justgu1/kubernetes-services.git
      targetRevision: main
      ref: values
    - repoURL: git@github.com:justgu1/kubernetes-services.git
      targetRevision: main
      path: chatwoot
  destination:
    server: https://kubernetes.default.svc
    namespace: chatwoot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true