apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: global-alerts
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  route:
    receiver: email-default
    groupBy: ['alertname', 'namespace']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    routes:
      - matchers:
          - name: severity
            value: critical
        receiver: email-default
        repeatInterval: 1h
      - matchers:
          - name: severity
            value: warning
        receiver: email-default
        repeatInterval: 6h
  receivers:
    - name: email-default
      emailConfigs:
        - to: "guilherme@justgui.dev"
          from: "support@justgui.dev"
          smarthost: "smtp.hostinger.com:465"
          authUsername: "support@justgui.dev"
          authPassword:
            name: alertmanager-smtp-secret
            key: SMTP_PASSWORD
          requireTLS: false   # porta 465 = SSL direto, não STARTTLS
          sendResolved: true
          tlsConfig:
            insecureSkipVerify: false
          headers:
            - key: Subject
              value: '[{{ "{{" }} .Status | toUpper {{ "}}" }}] {{ "{{" }} .CommonLabels.alertname {{ "}}" }}'
