---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: monitoring-basic-auth
  namespace: monitoring
spec:
  encryptedData:
    auth: AgAGZS3E100xZ4A1TdyRQg/cA/XG5L2dkanFfwkB4I8N+7YDsbqdauET2dhLEqYMUq4y25gyYymSOrujdf83Ho7NzKAM3a9GzApCuVIZH0urBTBWI8zIxVEIVSk8mwhQXTFLFHDAGxdx6r+t45yhEfXifpe2zDUejrN/H+lyGxhknmhNYHCP0vZIMJv+ueCk1iZ7uqlgyNUcCNcem1hQGUdRyBrA4BGjNDKHHt0NhGs/VqRSnkKLPBaYliFXdtIQA4WCvUbREQtB9mEAXJO9gsU+JPW8RGDPHslx9OoLyU6P395LeRcxAXwsdWor+YKI7skTOtUc+50KI4fMcYO/X7MJ4HlcWYmrZChnUdThPFiKr9rFCvctVpbdICzdSiQ4aH5TextVjUhcX+k3qfUBlJyNd2/qhARkx5PMD6HXDNNpzPIJtEU/NTESBJC9TFCepI/rYSHWj6qP9qzXSIDRc5bF+5aSN4jOPyCqb/pMxZ3dHODar9ZtZFXSV766aXManB7jIhK1gHum1JBxt5LeO9/hbX/8p6R2HI574aN8xAg93WHulS8dCqGhbPf3sYjIrKIZ+BNHVIVAIIzU5o1qONkjmUtfVpop3eXpSPNZcsC4XHmCYBbpR2K53XqGxYkkw+YTOorBiu7V29BnM+Z9NA+B+FzzOwigXFBjN7S4cuq9Q8msb3Gwjs5ue5Wz0K90C+dX5QQZWuTNcZYrjdx25jNoS/JVp9WVNc32WP1TtSkEPe/ZnC2977OYrIIDZ4I=
  template:
    metadata:
      creationTimestamp: null
      name: monitoring-basic-auth
      namespace: monitoring
