---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: monitoring-basic-auth
  namespace: monitoring
spec:
  encryptedData:
    auth: AgCXYgORUKETRH2n8G/KfOhdqx4Zvffdh861HKNtU/xkbF5IFvblO+ZfefMfal5OeyXu/6BNnknCbStZho4UIa6Xq0fFj3KVvAY8sGqa9ZcmUEwXM3PWIVDaBs6S2dU/99PSxHC/eLhPRcP0PqWaEraDE/gIpdKZKE0dWPwPkYD47PBcYB92i/LI4MGO73Mlh1CXxVuFeQVc3aax8JpN2VF/9jCUn2RoJlQuvkYoo1Zs4RoVsHevXbCCjsBW485VcZ5nPL+hZHMlS3z+j6ZG1kaVZhRvT0JDKDXMnrKvT+1lJKb6/JxTy3hTzaZcH6HDoci9bth5tueI364jX+ZZqEipohCilvH7c169Zbe+ABWQYRH9R/uIBTMsTvD8tyBXSg6iGzwVSlyg7DZs4TCq+3c7BO545bFHpYvpySDSqwier/QtlorGAV6HqdJe2cHJu9+NTlX0Q/lzI2FMiOeSVoMk25Eght9yQihEXqO3Yfi53pndWfV4642t4nii9QQ4Yt0NUQJjTm67wxhuIUQxTSEyWuguYmaHYj2xL1s9JZxcjUo/4SwBwkF/RQH8H9HvRlT2xOfk2WuHmyFNUTNItJHVoYesyhaFpcX+woZydFVU9EApYcw4K1RJ7ZeRb0+xRaaGU+y4nqLYDTkga+cjPQ8rhGJ4TCtEbDna/iiI59aGREyDo/YIQP2PYLLyAOVkuMH3I6CtFln+9TjJ9PQhJ7WVIx3y+Hdg4RWC4dhr/uSBFMV7RYKTh6qco6oYetw=
  template:
    metadata:
      name: monitoring-basic-auth
      namespace: monitoring
