apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-root-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: minio-root-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: secret/cluster/minio
